name: bambu_village_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_map: ^4.0.0
  flutter: 
    sdk: flutter
  latlong2: ^0.8.2
  flutter_map_marker_popup: ^5.0.0
  flutter_slider_drawer: ^2.1.3
  accordion: ^2.5.1

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - assets/data/json/marker.json


